name: Build blocklists

on:
  workflow_dispatch:
  branches:
    - trunk
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make

    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.3
      with:
        default_author: user_info

